export const DOCUMENT_TYPES = [
  { value: 'FA', label: 'FA — Fatura' },
  { value: 'FT', label: 'FT — Fatura Ticket' },
  { value: 'FR', label: 'FR — Fatura-Recibo' },
  { value: 'FG', label: 'FG — Fatura Global' },
  { value: 'GF', label: 'GF — Guia de Faturação' },
  { value: 'AC', label: 'AC — Fatura Cambial' },
  { value: 'AR', label: 'AR — Aviso de Recebimento' },
  { value: 'TV', label: 'TV — Talão de Venda' },
  { value: 'RC', label: 'RC — Recibo' },
  { value: 'RG', label: 'RG — Recibo Global' },
  { value: 'RE', label: 'RE — Recibo Eletrónico' },
  { value: 'ND', label: 'ND — Nota de Débito' },
  { value: 'NC', label: 'NC — Nota de Crédito' },
  { value: 'AF', label: 'AF — Anulação de Fatura' },
  { value: 'RP', label: 'RP — Recibo de Pagamento' },
  { value: 'RA', label: 'RA — Recibo de Adiantamento' },
  { value: 'CS', label: 'CS — Consulta de Serviço' },
  { value: 'LD', label: 'LD — Listagem de Documentos' },
];
